### ISSUE TITLE
eeptpu compiler error

### ISSUE THREAD

**Issue by Hong-333** [embedeep/EEP-TPU-SDK#1]
Hi
I followed the guide and installed protobuf and export opencv library path 
After that i run eeptpu_compiler but i failed 

$ ./eeptpu_compiler 
./eeptpu_compiler: symbol lookup error: ./eeptpu_compiler: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev

Why does this error occur?

**Comment by kanghanbich** [comment]
Hi, I am also having such a problem. I think it's a problem of protobuf.
I want to know the cause of the problem.
